### ISSUE TITLE
Unresponsive loop. 

### ISSUE THREAD

**Issue by Alphaemef** [oarcher/piotech#18]
Hi Again Oarcher.

Im running the PR build, and its fracking awesome. A few times, if I forget to enable the http server (so the unit doesn't have access) it will go into eternal fault mode. And need to be restarted before I can proceed. The unit is still alive, but in some sort of loop. I can't get any other data out from it other than a fault code "Error read data" and it won't listen to restart requests or similar. 
The fail safe boot is on default setting. 

This is all the log shows. 

![Screenshot 2023-11-26 at 16 17 06](https://github.com/oarcher/piotech/assets/113418735/ea23f175-6a06-4cc0-b442-848957fc0f1a)

**Comment by oarcher** [comment]
Hi again @Alphaemef ,
  Sorry for late answer, I was busy on another project.

Have you tried to force `safe_mode` to other values ?
  - `no`: Never attempt to flash at boot time.
  - `yes`: Always flash at boot time.
  - `fallback`: Retry at boot time if ota fail.   <- this is the default

(see [Documentation](https://deploy-preview-3291--esphome.netlify.app/components/ota_http))

My guess is that you might have flashed a firmware on a device that never used `ota_http` before. When you flash a firmware, the previous data partition is not wiped, so the global variable that handle `safe_mode` is not present on the data device. Do you have any additional clues to give me to confirm my intuition ?

For `http_server`, I don't understand your configuration: You are saying that `ota_http` works better *with* `http_server` ?  It's strange, because `http_server`  consume a lot of memory, which competes with `ota_http` especially if `https` is used. BTW, are you using `http` or `https`  ?

**Comment by Alphaemef** [comment]
> Hi again @Alphaemef , Sorry for late answer, I was busy on another project.
> 
> Have you tried to force `safe_mode` to other values ?
> 
> * `no`: Never attempt to flash at boot time.
> * `yes`: Always flash at boot time.
> * `fallback`: Retry at boot time if ota fail.   <- this is the default
> 
> (see [Documentation](https://deploy-preview-3291--esphome.netlify.app/components/ota_http))
> 
> My guess is that you might have flashed a firmware on a device that never used `ota_http` before. When you flash a firmware, the previous data partition is not wiped, so the global variable that handle `safe_mode` is not present on the data device. Do you have any additional clues to give me to confirm my intuition ?
> 
> For `http_server`, I don't understand your configuration: You are saying that `ota_http` works better _with_ `http_server` ? It's strange, because `http_server` consume a lot of memory, which competes with `ota_http` especially if `https` is used. BTW, are you using `http` or `https` ?

Thats a good theory, which unfortunately I can't elaborate much on. I think you might be right that the few times it happened it was on devices with freshly installed ota_HTTP, but I am actually not exactly sure. IN the beginning I used "yes", but now I just use default (so I don't specify it).  Im travelling abroad atm, but will try to do some tests when I come home to see if I can replicate it. 

I apologise. With http_server I meant just the webserver I have running with the files on them. I.e, when my webserver was offline or if the necessary permissions were not granted on the webserver to the ESP32 client, then the above mentioned loop would show up. 

I don't have http-server on the ESP32, but I use SSL for the server it connects to (MQTT) and the server with the files is also https.

**Comment by oarcher** [comment]
I see that this issue is still open. Do you have more info ?

I don't think that the error is related to `safe_mode`, but to the `http` part (network, or server).

See https://github.com/esphome/esphome/pull/5586#issuecomment-1979786348 for a tip that check that your device is able to reach your http server.

**Comment by Alphaemef** [comment]
> I see that this issue is still open. Do you have more info ?
> 
> I don't think that the error is related to `safe_mode`, but to the `http` part (network, or server).
> 
> See [esphome/esphome#5586 (comment)](https://github.com/esphome/esphome/pull/5586#issuecomment-1979786348) for a tip that check that your device is able to reach your http server.

SOrry, I haven't experienced this in a looooong time. Might have been something completely different. Thanks!
