### ISSUE TITLE
[ota_http] any chance to get suport for esp-idf?

### ISSUE THREAD

**Issue by cavamora** [oarcher/piotech#3]
Error when compiling:
This feature is incompatible with esp-idf.

**Comment by oarcher** [comment]
Currently, http_ota use upstream arduino/HTTPClient because it need to retrieve "Content-Length" header. But ongoing https://github.com/esphome/esphome/pull/3256 implement `http_request` for esp-idf, and will allow to retrieve  "Content-Length".

So as a first step, I will have to switch to `http_request` internal esphome component. 

I don't plan to do this in a near future, but it's on my todo-list.

**Comment by oarcher** [comment]
first step done in #12
